# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = Teste2.o ../Gerson/matheus/imu/MPU6050/MPU6050.o ../Gerson/matheus/imu/Kalman/Kalman.o ../Gerson/matheus/imu/i2c/I2Cdev.o
LINKOBJ  = Teste2.o ../Gerson/matheus/imu/MPU6050/MPU6050.o ../Gerson/matheus/imu/Kalman/Kalman.o ../Gerson/matheus/imu/i2c/I2Cdev.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Teste2.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Teste2.o: Teste2.cpp
	$(CPP) -c Teste2.cpp -o Teste2.o $(CXXFLAGS)

../Gerson/matheus/imu/MPU6050/MPU6050.o: ../Gerson/matheus/imu/MPU6050/MPU6050.cpp
	$(CPP) -c ../Gerson/matheus/imu/MPU6050/MPU6050.cpp -o ../Gerson/matheus/imu/MPU6050/MPU6050.o $(CXXFLAGS)

../Gerson/matheus/imu/Kalman/Kalman.o: ../Gerson/matheus/imu/Kalman/Kalman.cpp
	$(CPP) -c ../Gerson/matheus/imu/Kalman/Kalman.cpp -o ../Gerson/matheus/imu/Kalman/Kalman.o $(CXXFLAGS)

../Gerson/matheus/imu/i2c/I2Cdev.o: ../Gerson/matheus/imu/i2c/I2Cdev.cpp
	$(CPP) -c ../Gerson/matheus/imu/i2c/I2Cdev.cpp -o ../Gerson/matheus/imu/i2c/I2Cdev.o $(CXXFLAGS)
